matrix:
  include:        
    - os: windows
      language: shell
      before_install:
        - choco install innosetup 
        - uname -a
        - echo $PWD
        - whoami

script:
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      echo $PWD;
   fi
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      git clone https://github.com/bebbo/amiga-gcc;
   fi
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      wget https://franke.ms/msys64.zip;
      unzip msys64.zip
   fi
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      powershell -executionpolicy bypass -command "c:\\Users\\travis\\build\\bebbo\\crap0000\\msys64\\usr\\bin\\bash.exe --login buildwin";
   fi
