matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: c
      before_install:
        - sudo apt-get install -y make git gcc g++ lhasa libgmp-dev libmpfr-dev libmpc-dev flex gettext texinfo
        - sudo mkdir /opt/amiga && sudo chown $(whoami) /opt/amiga
  
    - os: osx
      osx_image: xcode9.4
      sudo: required
      language: c
      before_install:
        - brew install libmpc util-linux
        - brew tap discoteq/discoteq; brew install flock
        - sudo mkdir /opt/amiga && sudo chown $(whoami) /opt/amiga
        
    - os: windows
      language: shell
      before_install:
        - choco install msys2 innosetup
        - uname -a

script:
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
        cp buildwin /c/tools/msys64/home/bebbo;
        echo x >/c/pipe;
        cmd /c "start cmd /k c:\tools\msys64\usr\bin\bash -login buildwin";
        tail --follow=name --max-unchanged-stats=1 /c/pipe;
    else
        git clone https://github.com/bebbo/amiga-gcc;
        cd amiga-gcc;
        mkdir -p build-$(uname);
        make update -j2;
        make all -j2;
        tar czf amiga-gcc-$(uname)-tgz /opt/amiga;
    fi
 