os: windows
language: shell
cache:
  directories:
  - amiga
jobs:
  include:
  - stage: Setup cache
    script:
    - rm -rf amiga
    - mkdir -p amiga
  - stage: make binutils
    before_install:
    - powershell -command 'Set-MpPreference -DisableRealtimeMonitoring $true'
    - if [ ! -f msys64/usr/bin/bash.exe ]; then wget --progress=bar:force https://franke.ms/msys64.tgz; rm -rf msys64; tar xzf msys64.tgz; fi
    script:
    - git clone https://github.com/bebbo/amiga-gcc
    - powershell -executionpolicy bypass -command "msys64\\usr\\bin\\bash.exe --login -c 'cd amiga-gcc && (PREFIX=$(realpath amiga) make -j3 info binutils gdb gprof&); while [ ! -f $(realpath amiga)/bin/m68k-amigaos-gdb ]; do date; sleep 30; done'"
  - stage: make gcc
    before_install:
    - powershell -command 'Set-MpPreference -DisableRealtimeMonitoring $true'
    - if [ ! -f msys64/usr/bin/bash.exe ]; then wget --progress=bar:force https://franke.ms/msys64.tgz; rm -rf msys64; tar xzf msys64.tgz; fi
    script:
    - git clone https://github.com/bebbo/amiga-gcc
    - mkdir -p amiga-gcc/projects/binutils
    - touch    amiga-gcc/projects/binutils/configure
    - mkdir -p amiga-gcc/build-MSYS_NT-10.0/binutils
    - touch    amiga-gcc/build-MSYS_NT-10.0/binutils/Makefile
    - touch    amiga-gcc/build-MSYS_NT-10.0/binutils/_done
    - powershell -executionpolicy bypass -command "msys64\\usr\\bin\\bash.exe --login -c 'cd amiga-gcc && (PREFIX=$(realpath amiga) make -j3 gcc&); while [ ! -f $(realpath amiga)/bin/m68k-amigaos-gcc ]; do date; sleep 30; done'"
  - stage: make ndk
    before_install:
    - powershell -command 'Set-MpPreference -DisableRealtimeMonitoring $true'
    - if [ ! -f msys64/usr/bin/bash.exe ]; then wget --progress=bar:force https://franke.ms/msys64.tgz; rm -rf msys64; tar xzf msys64.tgz; fi
    script:
    - git clone https://github.com/bebbo/amiga-gcc
    - mkdir -p amiga-gcc/projects/binutils
    - touch    amiga-gcc/projects/binutils/configure
    - mkdir -p amiga-gcc/build-MSYS_NT-10.0/binutils
    - touch    amiga-gcc/build-MSYS_NT-10.0/binutils/Makefile
    - touch    amiga-gcc/build-MSYS_NT-10.0/binutils/_done
    - powershell -executionpolicy bypass -command "msys64\\usr\\bin\\bash.exe --login -c 'cd amiga-gcc && PREFIX=$(realpath amiga) make -j3 libamiga fd2sfd fd2pragma sfdc ndk ndk13 netinclude ira vasm vbcc vlink'"
  - stage: make newlib
    before_install:
    - powershell -command 'Set-MpPreference -DisableRealtimeMonitoring $true'
    - if [ ! -f msys64/usr/bin/bash.exe ]; then wget --progress=bar:force https://franke.ms/msys64.tgz; rm -rf msys64; tar xzf msys64.tgz; fi
    script:
    - git clone https://github.com/bebbo/amiga-gcc
    - mkdir -p amiga-gcc/build-MSYS_NT-10.0
    - mkdir -p amiga-gcc/projects/binutils
    - touch    amiga-gcc/projects/binutils/configure
    - mkdir -p amiga-gcc/projects/gcc
    - touch    amiga-gcc/projects/gcc/configure
    - touch    amiga-gcc/build-MSYS_NT-10.0/_lha_done
    - mkdir    amiga-gcc/download
    - touch    amiga-gcc/download/NDK39.lha
    - touch    amiga-gcc/projects/NDK_3.9.info
    - mkdir -p amiga-gcc/projects/fd2sfd
    - touch    amiga-gcc/projects/fd2sfd/configure
    - mkdir -p amiga-gcc/projects/fd2pragma
    - touch    amiga-gcc/projects/fd2pragma/makefile
    - mkdir -p amiga-gcc/build-MSYS_NT-10.0/binutils
    - touch    amiga-gcc/build-MSYS_NT-10.0/binutils/Makefile
    - touch    amiga-gcc/build-MSYS_NT-10.0/binutils/_done
    - mkdir -p amiga-gcc/build-MSYS_NT-10.0/gcc
    - touch    amiga-gcc/build-MSYS_NT-10.0/gcc/Makefile
    - touch    amiga-gcc/build-MSYS_NT-10.0/gcc/_done
    - mkdir -p amiga-gcc/build-MSYS_NT-10.0/fd2sfd
    - touch    amiga-gcc/build-MSYS_NT-10.0/fd2sfd/Makefile
    - mkdir -p amiga-gcc/build-MSYS_NT-10.0/fd2pragma
    - touch    amiga-gcc/build-MSYS_NT-10.0/fd2pragma/fd2pragma
    - mkdir -p amiga/bin
    - touch    amiga/bin/fd2sfd
    - touch    amiga/bin/fd2pragma
    - touch    amiga-gcc/build-MSYS_NT-10.0/fd2sfd/_done
    - touch    amiga-gcc/build-MSYS_NT-10.0/fd2pragma/_done
    - touch    amiga-gcc/build-MSYS_NT-10.0/ndk-include_ndk0
    - touch    amiga-gcc/build-MSYS_NT-10.0/ndk-include_ndk
    - powershell -executionpolicy bypass -command "msys64\\usr\\bin\\bash.exe --login -c 'cd amiga-gcc && (PREFIX=$(realpath amiga) make -j3 info newlib&); while [ ! -f $(realpath amiga)/m68k-amigaos/lib/libc.a ]; do date; sleep 30; done'"
  - stage: make libnix
    before_install:
    - powershell -command 'Set-MpPreference -DisableRealtimeMonitoring $true'
    - if [ ! -f msys64/usr/bin/bash.exe ]; then wget --progress=bar:force https://franke.ms/msys64.tgz; rm -rf msys64; tar xzf msys64.tgz; fi
    script:
    - git clone https://github.com/bebbo/amiga-gcc
    - mkdir -p amiga-gcc/build-MSYS_NT-10.0
    - mkdir -p amiga-gcc/projects/binutils
    - touch    amiga-gcc/projects/binutils/configure
    - mkdir -p amiga-gcc/projects/gcc
    - touch    amiga-gcc/projects/gcc/configure
    - touch    amiga-gcc/build-MSYS_NT-10.0/_lha_done
    - mkdir    amiga-gcc/download
    - touch    amiga-gcc/download/NDK39.lha
    - touch    amiga-gcc/projects/NDK_3.9.info
    - mkdir -p amiga-gcc/projects/fd2sfd
    - touch    amiga-gcc/projects/fd2sfd/configure
    - mkdir -p amiga-gcc/projects/fd2pragma
    - touch    amiga-gcc/projects/fd2pragma/makefile
    - mkdir -p amiga-gcc/build-MSYS_NT-10.0/binutils
    - touch    amiga-gcc/build-MSYS_NT-10.0/binutils/Makefile
    - touch    amiga-gcc/build-MSYS_NT-10.0/binutils/_done
    - mkdir -p amiga-gcc/build-MSYS_NT-10.0/gcc
    - touch    amiga-gcc/build-MSYS_NT-10.0/gcc/Makefile
    - touch    amiga-gcc/build-MSYS_NT-10.0/gcc/_done
    - mkdir -p amiga-gcc/build-MSYS_NT-10.0/fd2sfd
    - touch    amiga-gcc/build-MSYS_NT-10.0/fd2sfd/Makefile
    - mkdir -p amiga-gcc/build-MSYS_NT-10.0/fd2pragma
    - touch    amiga-gcc/build-MSYS_NT-10.0/fd2pragma/fd2pragma
    - mkdir -p amiga/bin
    - touch    amiga/bin/fd2sfd
    - touch    amiga/bin/fd2pragma
    - touch    amiga-gcc/build-MSYS_NT-10.0/fd2sfd/_done
    - touch    amiga-gcc/build-MSYS_NT-10.0/fd2pragma/_done
    - mkdir -p amiga-gcc/projects/sfdc
    - touch    amiga-gcc/projects/sfdc/configure
    - mkdir -p amiga-gcc/build-MSYS_NT-10.0/sfdc
    - touch    amiga-gcc/build-MSYS_NT-10.0/sfdc/Makefile
    - touch    amiga/bin/sfdc
    - touch    amiga-gcc/build-MSYS_NT-10.0/sfdc/_done
    - touch    amiga-gcc/build-MSYS_NT-10.0/ndk-include_ndk0
    - touch    amiga-gcc/build-MSYS_NT-10.0/ndk-include_ndk
    - touch    amiga-gcc/build-MSYS_NT-10.0/ndk-include_ndk13
    - mkdir -p amiga-gcc/projects/newlib-cygwin/newlib
    - touch    amiga-gcc/projects/newlib-cygwin/newlib/configure
    - mkdir -p amiga-gcc/build-MSYS_NT-10.0/newlib/newlib
    - touch    amiga-gcc/build-MSYS_NT-10.0/newlib/newlib/Makefile
    - touch    amiga-gcc/build-MSYS_NT-10.0/newlib/newlib/libc.a
    - touch    amiga-gcc/build-MSYS_NT-10.0/newlib/_done
    - mkdir -p amiga-gcc/projects/amiga-netinclude
    - touch    amiga-gcc/projects/amiga-netinclude/README.md
    - touch    amiga-gcc/build-MSYS_NT-10.0/_netinclude
    - powershell -executionpolicy bypass -command "msys64\\usr\\bin\\bash.exe --login -c 'cd amiga-gcc && (PREFIX=$(realpath amiga) make -j3 info libnix clib2 libgcc &); while [ ! -f $(realpath amiga)/m68k-amigaos/clib2/lib/libc.a ]; do date; sleep 30; done'"
  - stage: Create_setup
    before_install:
    - powershell -command 'Set-MpPreference -DisableRealtimeMonitoring $true'
    - choco install innosetup
    - if [ ! -f msys64/usr/bin/bash.exe ]; then wget --progress=bar:force https://franke.ms/msys64.tgz; rm -rf msys64; tar xzf msys64.tgz; fi
    script:
    - git clone https://github.com/bebbo/amiga-gcc
    - echo "#define MyAppVersion \"$(date +%Y%m%d)\"" > setup2.iss
    - sed amiga-gcc/setup/setup2.iss -e "s|\\\\msys64\\\\opt\\\\amiga|$(echo $PWD | sed 's|/|\\\\|g' | cut -b4-)\\\\amiga|g" >> setup2.iss
    - cp  amiga-gcc/setup/icon.ico .
    - cp  amiga-gcc/setup/hello.c amiga
    - cp  amiga-gcc/setup/cmdline.bat amiga
    - cp  amiga-gcc/setup/bat2exe.exe amiga/bin/
    - echo copy dlls
    - cp msys64/usr/bin/msys-iconv-2.dll   amiga/bin
    - cp msys64/usr/bin/msys-intl-8.dll    amiga/bin
    - cp msys64/usr/bin/msys-2.0.dll       amiga/bin
    - cp msys64/usr/bin/msys-z.dll         amiga/bin
    - cp msys64/usr/bin/msys-gcc_s-seh-1.dll amiga/bin
    - cp msys64/usr/bin/msys-stdc++-6.dll  amiga/bin
    - cp msys64/usr/bin/msys-mpfr-6.dll    amiga/bin
    - cp msys64/usr/bin/msys-mpc-3.dll     amiga/bin
    - cp msys64/usr/bin/msys-gmp-10.dll    amiga/bin
    - cp msys64/usr/bin/msys-ncursesw6.dll amiga/bin
    - cp msys64/usr/bin/iconv.exe amiga/bin
    - cp msys64/usr/bin/sh.exe    amiga/bin
    - cp msys64/usr/bin/rm.exe    amiga/bin
    - cp msys64/usr/bin/cp.exe    amiga/bin
    - cp msys64/usr/bin/uname.exe amiga/bin
    - cp msys64/usr/bin/which.exe amiga/bin
    - cp msys64/usr/bin/make.exe  amiga/bin/_make.exe
    - powershell -executionpolicy bypass -command "cmd /c 'c:\\Program Files (x86)\\Inno Setup 5\\ISCC.exe' setup2.iss"
deploy:
  provider: releases
  api_key:
    secure: uzw/mTfiU7sERb0znrbuZhCWsL8GWr8amI9lnpAQnYJ5iCzZRQjz5c2BKKYdmpXoX8NX+QAN8y4pDZCsVoPvozA7r5XceceH/uZUOgvNgI3K7dQB9KkpVXyQT0FGJcWAbgiBq5YbvYK/EpdV+DNqSWZnEjDUUfxc9+Pxbdqp3D71D4lgBEAPIdFb0Ikb4tz/Dj0qtOUR55afZpCe3mX/vVkQ1POyuKCAKMVkDfxqUNNwPVOhUIU+qWS4epMcZZF+HRwNmgD2UTCeZSiBGzTRoRtkqOd4nDze7xOgKAWiZ5doPopKbNfkRA1I1IpHo53IhpVhM813KJOA5SXla2OjMX8mRoj2//4vPwdwLdYKS2n5sx5XrWJLYQRvjmajP295Bw8V1M9tlQ/gPiyd633WGk20PrgnZ0RoRdzLGYDHHxXfQ38/o8slMnej3X7I7bbkBUC1GgA3Ti4LtMlIHG0XoOv+Ucp9Hyaly5bOmA1/XDJH2m/pHqFF0HZsu1rND/GA3tFrHw5Qj7jYsU2b0flpoa1hKdTzDC1eIe8MivhobwYrS8QcFFnENyeZqfoV4ItvTUTepArnToEY8gBl8I0zuWDEJDHtuPNtELfRnHy36wMUbiE3o0vCt+VI1WsAjyOGuIZMsc8uP+hUltCRYXpbf7VQsliFw+Nc4PLHfM+3GoY=
  file: Output/setup-amiga-gcc.exe
  skip_cleanup: true
  draft: true
  on:
    condition: ${TRAVIS_BUILD_STAGE_NAME} == Create_setup
