os: windows
language: shell
cache:
  directories:
  - /c/Users/travis/build/bebbo/crap0000/amiga/
jobs:
  include:
  - stage: Setup cache
    script:
    - rm -rf amiga msys64
    - mkdir -p amiga
  - stage: make binutils
    before_install:
    - if [ ! -f msys64/usr/bin/bash.exe ]; then wget --progress=bar:force https://franke.ms/msys64.tgz; rm -rf msys64; tar xzf msys64.tgz; fi
    script:
    - git clone https://github.com/bebbo/amiga-gcc
    - powershell -executionpolicy bypass -command "msys64\\usr\\bin\\bash.exe --login -c 'cd amiga-gcc && (PREFIX=$(realpath amiga) make -j3 info binutils gdb gprof&); while [ ! -f $(realpath amiga)/bin/m68k-amigaos-gdb ]; do date; sleep 30; done'"
  - stage: make gcc
    before_install:
    - if [ ! -f msys64/usr/bin/bash.exe ]; then wget --progress=bar:force https://franke.ms/msys64.tgz; rm -rf msys64; tar xzf msys64.tgz; fi
    script:
    - git clone https://github.com/bebbo/amiga-gcc
    - mkdir -p      amiga-gcc/projects/binutils
    - echo "fake" > amiga-gcc/projects/binutils/configure
    - mkdir -p      amiga-gcc/build-MSYS_NT-10.0/binutils 
    - echo "fake" > amiga-gcc/build-MSYS_NT-10.0/binutils/Makefile
    - echo "done" > amiga-gcc/build-MSYS_NT-10.0/binutils/_done
    - powershell -executionpolicy bypass -command "msys64\\usr\\bin\\bash.exe --login -c 'cd amiga-gcc && ((PREFIX=$(realpath amiga) make -j3 info gcc&); while [ ! -f $(realpath amiga)/bin/m68k-amigaos-gcc ]; do date; sleep 30; done'"
  - stage: make ndk
    before_install:
    - if [ ! -f msys64/usr/bin/bash.exe ]; then wget --progress=bar:force https://franke.ms/msys64.tgz; rm -rf msys64; tar xzf msys64.tgz; fi
    script:
    - git clone https://github.com/bebbo/amiga-gcc
    - mkdir -p      amiga-gcc/projects/binutils
    - echo "fake" > amiga-gcc/projects/binutils/configure
    - mkdir -p      amiga-gcc/build-MSYS_NT-10.0/binutils 
    - echo "fake" > amiga-gcc/build-MSYS_NT-10.0/binutils/Makefile
    - echo "done" > amiga-gcc/build-MSYS_NT-10.0/binutils/_done
    - powershell -executionpolicy bypass -command "msys64\\usr\\bin\\bash.exe --login -c 'cd amiga-gcc && PREFIX=$(realpath amiga) make -j3 info ndk ndk13'"
  - stage: make newlib
    before_install:
    - if [ ! -f msys64/usr/bin/bash.exe ]; then wget --progress=bar:force https://franke.ms/msys64.tgz; rm -rf msys64; tar xzf msys64.tgz; fi
    script:
    - git clone https://github.com/bebbo/amiga-gcc
    - mkdir -p      amiga-gcc/projects/binutils
    - echo "fake" > amiga-gcc/projects/binutils/configure
    - mkdir -p      amiga-gcc/build-MSYS_NT-10.0/binutils 
    - echo "fake" > amiga-gcc/build-MSYS_NT-10.0/binutils/Makefile
    - echo "done" > amiga-gcc/build-MSYS_NT-10.0/binutils/_done
    - mkdir -p      amiga-gcc/build-MSYS_NT-10.0/gcc
    - echo "done" > amiga-gcc/build-MSYS_NT-10.0/gcc/_done
    - echo "done" > amiga-gcc/build-MSYS_NT-10.0/ndk-include_ndk
    - powershell -executionpolicy bypass -command "msys64\\usr\\bin\\bash.exe --login -c 'cd amiga-gcc && (PREFIX=$(realpath amiga) make -j3 info newlib&); while [ ! -f $(realpath amiga)/m68k-amigaos/lib/libc.a ]; do date; sleep 30; done'"
  - stage: make libnix
    before_install:
    - if [ ! -f msys64/usr/bin/bash.exe ]; then wget --progress=bar:force https://franke.ms/msys64.tgz; rm -rf msys64; tar xzf msys64.tgz; fi
    script:
    - git clone https://github.com/bebbo/amiga-gcc
    - mkdir -p      amiga-gcc/projects/binutils
    - echo "fake" > amiga-gcc/projects/binutils/configure
    - mkdir -p      amiga-gcc/build-MSYS_NT-10.0/binutils 
    - echo "fake" > amiga-gcc/build-MSYS_NT-10.0/binutils/Makefile
    - echo "done" > amiga-gcc/build-MSYS_NT-10.0/binutils/_done
    - mkdir -p      amiga-gcc/build-MSYS_NT-10.0/gcc
    - echo "done" > amiga-gcc/build-MSYS_NT-10.0/gcc/_done
    - mkdir -p      amiga-gcc/build-MSYS_NT-10.0/newlib
    - echo "done" > amiga-gcc/build-MSYS_NT-10.0/newlib/_done
    - echo "done" > amiga-gcc/build-MSYS_NT-10.0/ndk-include_ndk
    - echo "done" > amiga-gcc/build-MSYS_NT-10.0/ndk-include_ndk
    - powershell -executionpolicy bypass -command "msys64\\usr\\bin\\bash.exe --login -c 'cd amiga-gcc && (PREFIX=$(realpath amiga) make -j3 info libnix clib2&); while [ ! -f $(realpath amiga)/m68k-amigaos/clib2/lib/libc.a ]; do date; sleep 30; done'"
  - stage: Create_setup
    before_install:
    - choco install innosetup
    script:
    - git clone https://github.com/bebbo/amiga-gcc
    - echo "#define MyAppVersion \"$(date +%Y%m%d)\"" > setup2.iss
    - sed amiga-gcc/setup/setup2.iss -e "s|\\\\msys64\\\\opt\\\\amiga|$(echo $PWD | sed 's|/|\\\\|g' | cut -b4-)\\\\amiga|g" >> setup2.iss
    - cp  amiga-gcc/setup/icon.ico .
    - cp  amiga-gcc/setup/hello.c amiga
    - cp  amiga-gcc/setup/cmdline.bat amiga
    - cp  amiga-gcc/setup/bat2exe.exe amiga/bin/
    - echo copy dlls
    - cp msys64/usr/bin/msys-iconv-2.dll   amiga/bin
    - cp msys64/usr/bin/msys-intl-8.dll    amiga/bin
    - cp msys64/usr/bin/msys-2.0.dll       amiga/bin
    - cp msys64/usr/bin/msys-z.dll         amiga/bin
    - cp msys64/usr/bin/msys-gcc_s-seh-1.dll amiga/bin
    - cp msys64/usr/bin/msys-stdc++-6.dll  amiga/bin
    - cp msys64/usr/bin/msys-mpfr-6.dll    amiga/bin
    - cp msys64/usr/bin/msys-mpc-3.dll     amiga/bin
    - cp msys64/usr/bin/msys-gmp-10.dll    amiga/bin
    - cp msys64/usr/bin/msys-ncursesw6.dll amiga/bin
    - cp msys64/usr/bin/iconv.exe amiga/bin
    - cp msys64/usr/bin/sh.exe    amiga/bin
    - cp msys64/usr/bin/rm.exe    amiga/bin
    - cp msys64/usr/bin/cp.exe    amiga/bin
    - cp msys64/usr/bin/uname.exe amiga/bin
    - cp msys64/usr/bin/which.exe amiga/bin
    - cp msys64/usr/bin/make.exe  amiga/bin/_make.exe
    - powershell -executionpolicy bypass -command "cmd /c 'c:\\Program Files (x86)\\Inno Setup 5\\ISCC.exe' setup2.iss"
deploy:
  provider: releases
  api_key:
    secure: ahFeqlMYR6x9DA01B4NeBAqNKqv+ZxJoM0fpQrCzeKI+szah6M3THhhP8XO/PTBhUbM865wpoVg5J+l7GxFtH/Q7AB2wA1sEhpt79FhT4j43Ek8h5E18GKG9UGVZWRLDfhor6ewo3gjf8Q8Tw14MH5H4qdXbxQIHyU3PWoBuIX2Z63/8ad2CWAcSiAaqpK4wzKqR73cjHEH8xHJp5+Q1e5kEsvlksbu95pEVPqndpQ/9HUetwqgR/U6A0dPdY4GcQM8AX17SmvzbXrAOqRhegOg2/j2FnKa/w2m8WD89CxRDW/roRgCOOTe0JleBVqZzuLNaPHu/aRnTSC7wt4SfDbh/WVp1XfZKI5Y49evaljzx11C5PWpqaUk9n3ITg9bGxXcNbgYKo96S6chR33mlBdZWDt/3bWeQGp+liNiUMM57kRpxsLNP3yMNkvxVxAIJ/xMe+FWUJuKwMD/dLDNuTS+vqH0ezLAbuwWLn92G/9OPw24CRrusZ7OPQuZFenDBBj0kM4+1n11JksGgPwF43hPJbXs6u6CQAxVeYYzCMziF3klidoIqiFKz4cmyvxB73cWqRBGP2cr+qworJp41pNnazklRAgVUgoxqWLUNEqHzJ+qU21T1EpoaYXqdcMEv5SBQhOpv/bQmSXU25MGA7VlMrnxTziqVvztKZcA0jyo=
  repo: bebbo/amiga-gcc
  file: Output/setup-amiga-gcc.exe
  skip_cleanup: true
  draft: true
  on:
    condition: ${TRAVIS_BUILD_STAGE_NAME} == Create_setup
 