matrix:
  include:        
    - os: windows
      language: shell
      before_install:
        - apt-get xz
        - choco install innosetup 
        - uname -a
        - echo $PWD

script:
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      echo $PWD;
   fi
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      git clone https://github.com/bebbo/amiga-gcc;
   fi
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      wget --progress=bar:force https://franke.ms/msys64.tgz;
   fi
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      tar xf msys64.tgz;
   fi
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      travis_wait 60 powershell -executionpolicy bypass -command "c:\\Users\\travis\\build\\bebbo\\crap0000\\msys64\\usr\\bin\\bash.exe --login -c 'cd /c/Users/travis/build/bebbo/crap0000/amiga-gcc ; make -j3 all'";
   fi
