os: windows
language: shell
cache:
  directories:
  - /c/Users/travis/build/bebbo/crap0000/amiga/
before_install:
- if [ "${TRAVIS_BUILD_STAGE_NAME}" != "Clear cache" ]; then wget --progress=bar:force https://franke.ms/msys64.tgz; tar xzf msys64.tgz; fi
jobs:
  include:
  - stage: Clear cache
    script:
    - rm -rf amiga
    - mkdir -p amiga
  - stage: make binutils
    script:
    - git clone https://github.com/bebbo/amiga-gcc
    - powershell -executionpolicy bypass -command "msys64\\usr\\bin\\bash.exe --login -c 'cd amiga-gcc && PREFIX=$(realpath amiga) make -j3 info binutils gdb gprof'"
  - stage: make gcc
    script:
    - git clone https://github.com/bebbo/amiga-gcc
    - mkdir -p      amiga-gcc/projects/binutils
    - echo "fake" > amiga-gcc/projects/binutils/configure
    - mkdir -p      amiga-gcc/build-MSYS_NT-10.0/binutils 
    - echo "fake" > amiga-gcc/build-MSYS_NT-10.0/binutils/Makefile
    - echo "done" > amiga-gcc/build-MSYS_NT-10.0/binutils/_done
    - powershell -executionpolicy bypass -command "msys64\\usr\\bin\\bash.exe --login -c 'cd amiga-gcc && (PREFIX=$(realpath amiga) make -j3 info gcc&); while [ ! -f $(realpath amiga)/bin/m68k-amigaos-gcc ]; do date; sleep 30; done'"
  - stage: make ndk
    script:
    - git clone https://github.com/bebbo/amiga-gcc
    - powershell -executionpolicy bypass -command "msys64\\usr\\bin\\bash.exe --login -c 'cd amiga-gcc && PREFIX=$(realpath amiga) make -j3 info ndk ndk13'"
  - stage: create setup
    script:
    - choco install innosetup
    - powershell -executionpolicy bypass -command "c:\\tools\\msys64\\usr\\bin\\bash.exe --login -c 'echo todo innosetup'"
