matrix:
  include:        
    - os: windows
      language: shell
      before_install:
        - choco install innosetup 
        - uname -a
        - echo $PWD

script:
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      echo $PWD;
   fi
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      git clone https://github.com/bebbo/amiga-gcc;
   fi
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      cd amiga-gcc; while read p; do echo "/opt/amiga/m68k-amigaos/ndk-include/${p}:"; done < patches/ndk13/hfiles;
   fi 
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      wget --progress=bar:force https://franke.ms/msys.tgz;
   fi
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      tar xzf msys.tgz;
   fi
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      powershell -executionpolicy bypass -command "c:\\Users\\travis\\build\\bebbo\\crap0000\\msys64\\usr\\bin\\bash.exe --login -c 'cd /c/Users/travis/build/bebbo/crap0000/amiga-gcc ; make -j3 ndk13'";
   fi
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      powershell -executionpolicy bypass -command "c:\\Users\\travis\\build\\bebbo\\crap0000\\msys64\\usr\\bin\\bash.exe --login -c 'cd /c/Users/travis/build/bebbo/crap0000/amiga-gcc ; make -j3 ndk13'";
   fi
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      powershell -executionpolicy bypass -command "c:\\Users\\travis\\build\\bebbo\\crap0000\\msys64\\usr\\bin\\bash.exe --login -c 'cd /c/Users/travis/build/bebbo/crap0000/amiga-gcc ; make -j3 all'";
   fi
