matrix:
  include:        
    - os: windows
      language: shell
      before_install:
        - choco install innosetup 
        - uname -a
        - echo $PWD
      cache:
        directories:
        - ./msys64/
      jobs:
        include:
          - stage: foo
            script:
            - uname

script:
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      echo $PWD;
   fi
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      git clone https://github.com/bebbo/amiga-gcc;
   fi
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      wget --progress=bar:force https://franke.ms/msys64.tgz;
   fi
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      tar xzf msys64.tgz;
   fi
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      powershell -executionpolicy bypass -command "c:\\Users\\travis\\build\\bebbo\\crap0000\\msys64\\usr\\bin\\bash.exe --login -c 'cd /c/Users/travis/build/bebbo/crap0000/amiga-gcc ; make -j3 binutils projects/gcc/configure'";
   fi
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      powershell -executionpolicy bypass -command "c:\\Users\\travis\\build\\bebbo\\crap0000\\msys64\\usr\\bin\\bash.exe --login -c 'cd /c/Users/travis/build/bebbo/crap0000/amiga-gcc ; make -j3 gdb'";
   fi
