os: windows
language: shell
before_install:
- choco install innosetup 
- uname -a
- echo $PWD
cache:
  directories:
  - ./msys64/
jobs:
  include:
  - stage: load cache
    script:
    - uname
    - wget --progress=bar:force https://franke.ms/msys64.tgz
    - rm -rf ../msys64
    - tar -C .. xzf msys64.tgz
    - powershell -executionpolicy bypass -command "..\\msys64\\usr\\bin\\bash.exe --login -c 'echo $PWD'"

