os: windows
language: shell
before_install:
- choco install innosetup 
- uname -a
- echo $PWD
cache:
  directories:
  - ./build/bebbo/crap0000/msys64/
  - ./build/bebbo/crap0000/amiga/
jobs:
  include:
  - stage: load cache
    script:
    - uname
    - wget --progress=bar:force https://franke.ms/msys64.tgz
    - rm -rf msys64
    - tar xzf msys64.tgz
    - mkdir amiga
    - powershell -executionpolicy bypass -command "msys64\\usr\\bin\\bash.exe --login -c 'echo $PWD'"
  - stage: make binutils
    script:
    - git clone https://github.com/bebbo/amiga-gcc
    - powershell -executionpolicy bypass -command "msys64\\usr\\bin\\bash.exe --login -c 'cd amiga-gcc && PREFIX=$(realpath ../amiga) make info binutils'"
    - ls -l amiga-gcc/build-MSYS_NT-10.0
    - ls -l amiga-gcc/build-MSYS_NT-10.0/binutils
  - stage: make ndk
    script:
    - git clone https://github.com/bebbo/amiga-gcc
    - powershell -executionpolicy bypass -command "msys64\\usr\\bin\\bash.exe --login -c 'cd amiga-gcc && PREFIX=$(realpath ../amiga) make info ndk ndk13'"
    - ls -l amiga-gcc/build-MSYS_NT-10.0

