matrix:
  include:        
    - os: windows
      language: shell
      before_install:
        - choco install innosetup 
        - uname -a
        - echo $PWD

script:
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      echo $PWD;
   fi
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      git clone https://github.com/bebbo/amiga-gcc;
   fi
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      while read ii; do echo "/opt/amiga/m68k-amigaos/ndk-include/$ii:"; done < amiga-gcc/patches/ndk13/hfiles;
   fi 
