matrix:
  include:        
    - os: windows
      language: shell
      before_install:
        - choco install msys2 innosetup 
        - uname -a
        - echo $PWD
        - whoami

script:
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      echo $PWD;
      git clone https://github.com/bebbo/amiga-gcc;
      powershell -executionpolicy bypass -command "c:\\tools\\msys64\\usr\\bin\\bash.exe --login buildwin";
   fi
