matrix:
  include:        
    - os: windows
      language: shell
      before_install:
        - uname -a
        - echo $PWD
        - whoami

script:
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      echo $PWD;
      git clone https://github.com/bebbo/amiga-gcc;
      powershell -executionpolicy bypass -command {dir c:\\tools}
   fi
