language: c

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" -a -z "$config" ]; then 
      sudo apt-get install -y make git gcc g++ lhasa libgmp-dev libmpfr-dev libmpc-dev flex gettext texinfo;
    else
      echo "$TRAVIS_OS_NAME";
    fi
  - git clone https://github.com/bebbo/amiga-gcc
    
script:
 - cd amiga-gcc && make info
