matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: c
      before_install:
        - sudo apt-get install -y make git gcc g++ lhasa libgmp-dev libmpfr-dev libmpc-dev flex gettext texinfo
        - sudo mkdir /opt/amiga && sudo chown $(whoami) /opt/amiga
  
    - os: osx
      osx_image: xcode9.4
      sudo: required
      language: c
      before_install:
        - brew install libmpc util-linux
        - brew tap discoteq/discoteq; brew install flock
        - sudo mkdir /opt/amiga && sudo chown $(whoami) /opt/amiga
        
    - os: windows
      language: shell
      before_install:
        - choco install msys2 innosetup
        - uname -a
        - echo $PWD
        - whoami

script:
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
        cp buildwin /c/tools/msys64/home/travis;
        echo x >/c/tools/pipe;
        cmd /c "start cmd /k c:\\tools\\msys64\\usr\\bin\\bash --login /home/travis/buildwin";
        tail --follow=name --max-unchanged-stats=1 /c/tools/pipe || echo "EOF";
        ls -l Output;
    else
        git clone https://github.com/bebbo/amiga-gcc;
        cd amiga-gcc;
        mkdir -p build-$(uname);
        make update -j2;
        make all -j2;
        tar czf amiga-gcc-$(uname)-$(date +%Y%m%d).tgz /opt/amiga;
        ls -l;
    fi
 