version: 1.0.{build}
build_script:
 - appveyor AddMessage -Category Information "instl 1"
 - cmd: cinst innosetup 
 - appveyor AddMessage -Category Information "instl 2"
 - cmd: cinst msys2 --params "/NoUpdate"
 - appveyor AddMessage -Category Information "build script started"
 - cmd: c:\tools\msys64\usr\bin\bash.exe --login -c "echo $(uname) $PWD $(whoami)"
 - cmd: c:\tools\msys64\usr\bin\bash.exe --login -c "pacman --noconfirm -S rsync git flex base-devel gcc gmp-devel mpc-devel mpfr-devel ncurses-devel"
 - cmd: c:\tools\msys64\usr\bin\bash.exe --login -c "cd /c/projects/crap0000 && wget https://franke.ms/a.tgz && tar xzf a.tgz"
 - cmd: c:\tools\msys64\usr\bin\bash.exe --login -c "mkdir -p /opt/amiga && cd /c/projects/crap0000/amiga-gcc && make update -j"
 - cmd: c:\tools\msys64\usr\bin\bash.exe --login -c "cd /c/projects/crap0000/amiga-gcc && make all -j4 || tar czf logs.tgz log/*"
 - cmd: c:\tools\msys64\usr\bin\bash.exe --login -c "echo yehaw"
 
artifacts:
 - path: amiga-gcc
   name: logs.tgz